from typing import Iterable
from pykakasi import kakasi
from hangul_romanize.rule import academic
from hangul_romanize import Transliter
from pypinyin import lazy_pinyin
import regex as re
ddd = [
    "As Long As You Love Me (feat. Big Sean)",
    "Bleeding Love",
    "Breakaway",
    "DJ Got Us Fallin' In Love (feat. Pitbull)",
    "Dynamite",
    "Fighter",
    "I Knew You Were Trouble.",
    "I Will Always Love You",
    "Lights (Single Version)",
    "Lose Yourself",
    "Mine",
    "Mr. Know It All",
    "My Life Would Suck Without You",
    "One Day",
    "Part of Me",
    "Price Tag",
    "Secrets",
    "When Will My Life Begin?",
    "Wish You Were Here",
    "吴克群",
    "My Heart Will Go On",
    "Take A Bow",
    "99 Times",
    "Better In Time (Single Mix)",
    "Just the Way You Are",
    "Nothings Gonna Change My Love For You",
    "Remember the Name (Non-PA Version)",
    "Since U Been Gone",
    "What Doesn't Kill You (Stronger)",
    "What the Hell",
    "When Will My Life Begin? (Reprise 1)",
    "牵牵牵手",
    "Back to December",
    "Behind These Hazel Eyes",
    "Burning",
    "Dark Side",
    "The Kiss",
    "Because of You",
    "Speak Now",
    "将军令",
    "为你写诗",
    "Crash and Burn",
    "Never Say Never",
    "Only Girl (In The World)",
    "Already Gone",
    "California King Bed",
    "Hush Hush; Hush Hush",
    "I See the Light",
    "My Happy Ending",
    "Healing Incantation",
    "Enchanted",
    "A Moment Like This",
    "Love The Way You Lie (Part II) (feat. Eminem)",
    "Before Your Love",
    "Need You Now",
    "Apologize (feat. Timbaland)",
    "I See You",
    "You Are Not Alone",
    "21 Guns",
    "F**kin' Perfect",
    "Boyfriend",
    "TiK ToK",
    "We Are Never Ever Getting Back Together",
    "第一次",
    "画心",
    "勇气",
    "约定",
    "Teenage Dream",
    "Last Friday Night (T.G.I.F.)",
    "遇见",
    "Firework",
    "The One That Got Away",
    "E.T.",
    "Nothing's Gonna Changes My Love For You",
    "至少还有你",
    "It Will Rain",
    "会呼吸的痛",
    "童話",
    "好不容易",
    "开始懂了",
    "我怀念的",
    "A Thousand Years",
    "Red Bean",
    "记得",
    "天高地厚",
    "Remember",
    "Wonderful Tonight",
    "Moon River",
    "你要的爱",
    "我的歌声里",
    "Catch My Breath",
    "Wide Awake",
    "TRY AGAIN",
    "X",
    "メグメル",
    "爱你的宿命",
    "暗香",
    "猜不透",
    "残酷な天使のテーゼ",
    "長い間",
    "大哥",
    "多远都要在一起",
    "光の戦士たち(TVサイズ)",
    "光辉岁月",
    "后会无期",
    "就是我",
    "恋に恋して",
    "梦里花",
    "那些年",
    "你把我灌醉",
    "欧若拉",
    "陪你度过漫长岁月",
    "瞬间",
    "突然好想你",
    "唯一",
    "我不愿让你一个人",
    "我好想你",
    "喜欢你",
    "下一个天亮",
    "想你的365天",
    "小幸运 (电影「我的少女时代」主题曲)",
    "一生所爱",
    "一直很安静",
    "隐形的翅膀",
    "勇気があれば",
    "再见",
    "知足",
    "只对你说",
    "走在冷风中",
    "My Destiny",
    "Super Star",
    "You Raise Me Up",
    "ウィニング・ラン!-風になりたい",
    "ペガサス幻想",
    "她说",
    "Do You Want to Build a Snowman?",
    "爱笑的眼睛",
    "新不了情",
    "For the First Time in Forever",
    "浮夸",
    "如果没有你",
    "小酒窩 (粵)",
    "只对你有感觉",
    "Love Is an Open Door",
    "爱,很简单",
    "冰心锁 (Cantonese Version)",
    "当你",
    "对不起我爱你",
    "Let It Go",
    "过火",
    "一眼万年",
    "夢の涯てまでも",
    "漂洋过海来看你",
    "GET THE WORLD",
    "I Love You (爱很简单)",
    "心墙",
    "最佳损友",
    "Tune-up Generation",
    "我很想爱他",
    "Let It Go (Single Version)",
    "记得",
    "GET THE WORLD~version XTO",
    "レット・イット・ゴー - ありのままで ",
    "다 잊어 (Korean Version)",
    "Let It Go",
    "Butter-Fly",
    "Fly Away",
    "I Believe",
    "Komm, susser Tod",
    "Time after time～花舞う街で～",
    "不潮不用花钱",
    "不为谁而做的歌",
    "不想懂得",
    "曹操",
    "传奇",
    "存在",
    "第二天堂",
    "第几个一百天",
    "飞得更高",
    "改变自己",
    "给我一个理由忘记",
    "后来",
    "倔强",
    "两个人的烟火",
    "龙卷风",
    "命运旋转之轮",
    "木乃伊",
    "那些花儿",
    "你的背包",
    "你就不要想起我",
    "怒放的生命",
    "暖暖",
    "是非题",
    "淘汰",
    "天地在我心",
    "团子大家族 (だんご大家族)",
    "新地球",
    "学不会",
    "一个像夏天一个像秋天",
    "依然爱你",
    "最初的梦想",
    "爱如潮水",
    "迷宫",
    "隨它吧 (Chinese Mandarin Version)",
    "放开手 (Taiwanese Mandarin Version)",
    "富士山下",
    "完美新世界",
    "I wish",
    "Try",
    "Yesterday",
    "爱就一个字",
    "编号89757",
    "翅膀",
    "故事细腻",
    "好心分手",
    "你不是真正的快乐",
    "抛物线",
    "亲爱的那并不是爱情",
    "晴天",
    "水仙",
    "天黑黑",
    "我愿意",
    "下雨天",
    "小酒窝",
    "小情歌",
    "烟花易冷",
    "月牙湾",
    "レット・イット・ゴー - ありのままで (Japanese End Credit Version)",
    "다 잊어 (Korean End Credit Version)",
    "随她吧",
    " Lydia",
    "Just Give Me a Reason",
    "keep on",
    "K歌之王",
    "Rage your dream",
    "到不了",
    "黑武士",
    "红玫瑰",
    "红色高跟鞋",
    "浪漫血液",
    "那些你很冒险的梦",
    "你不知道的事",
    "泡沫",
    "莎士比亚的天份",
    "失落沙洲",
    "十年",
    "突然好想你",
    "When You're Gone",
    "东风破",
    "冻结",
    "豆浆油条",
    "还是要幸福",
    "黑键",
    "可不可以不勇敢",
    "你的爱",
    "突然累了",
    "温柔",
    "我们的爱",
    "我们的歌",
    "我们的纪念日",
    "原来",
    "醉赤壁",
    "Kiss Goodbye",
    "Photograph",
    "背对背拥抱",
    "不死之身",
    "江南",
    "可惜不是你",
    "你不是真正的快乐",
    "身骑白马",
    "手心的蔷薇",
    "我爱他",
    "Always Online",
    "爱情yogurt",
    "不要说话",
    "但愿人长久",
    "害怕",
    "简简单单",
    "可惜沒如果",
    "I Am Alive",
    "Innocence",
    "忽然之间",
    "无尽的思念",
    "Too Bad",
    "爱不会绝迹",
    "如果你也听说",
    "The Biggest Dreamer",
    "会有那么一天",
    "茉莉雨",
    "我还想她",
    "转动",
    "Someone Like You",
    "点一把火炬",
    "妈妈的娜鲁娃",
    "七月七日晴",
    "生生",
    "温柔",
    "我的骄傲",
    "遗失的美好",
    "Days -愛情と日常-",
    "Love U U",
    "美人鱼",
    "期待爱",
    "一千年以后",
    "被风吹过的夏天",
    "表达爱",
    "距离",
    "人海中遇见你",
    "神智学無き戦い!",
    "爱与希望",
    "Beauty and the Beast (Soundtrack from the Motion Picture)",
    "Flightless Bird",
    "只要有你的地方",
    "美丽的神话Ⅱ",
    "挥着翅膀的女孩 (国)",
    "心中的日月",
    "不能说的秘密",
    "I Belive",
    "Knockin' on Heaven's Door",
    "No Boy No Cry",
    "NY, NY",
    "趁早",
    "春天里",
    "当太阳依旧升起",
    "掉了",
    "分手快乐",
    "海阔天空",
    "霍元甲",
    "空白格",
    "魔訶不思議アドベンチャー!",
    "宁夏",
    "失くした言葉",
    "拯救",
    "Brave Heart",
    "Die Young",
    "Dilemma (feat. Kelly Rowland)",
    "I Love You",
    "Payphone (feat. Wiz Khalifa)",
    "Rolling In The Deep",
    "断点",
    "光年之外",
    "燃えてヒーロー ",
    "圣诞结",
    "夜曲",
    "约定",
    "我不会唱歌",
    "一颗心的距离",
    "七里香",
    "杀手",
    "昨天",
    "酷愛",
    "独家记忆",
    "发如雪",
    "借口",
    "星晴",
    "直到世界的尽头",
    "西界",
    "左边",
    "单车",
    "枫",
    "搁浅",
    "黑色幽默",
    "月半小夜曲",
    "Zenzenzense (Movie Version)",
    "发现爱",
    "龙卷风",
    "末班车",
    "阴天快乐",
    "珊瑚海(feat. 梁心颐)",
    "你给我听好",
    "一路向北",
    "Nandemonaiya (Movie Version)",
    "Counting Stars",
    "Stay With Me",
    "说散就散",
    "体面",
    "一个人想着一个人",
    "一生所爱(电影'西游记大结局之仙履奇缘'插曲)",
    "因你而在",
    "追光者",
    "みちしるべ",
    "暧昧",
    "半岛铁盒",
    "彩虹",
    "房间",
    "零度的親吻",
    "半岛铁盒",
    "黑暗骑士",
    "青花瓷",
    "给我一首歌的时间",
    "妥协",
    "修炼爱情",
    "蒲公英的约定",
    "简单爱",
    "怎样",
    "ヤキモチ",
    "弱点",
    "回到过去",
    "裂缝中的阳光",
    "七里香",
    "晴天",
    "甜甜的",
    "最长的电影",
    "最长的电影",
    "以后要做的事",
    "保卫黄河",
    "康定情歌",
    "浏阳河",
    "在那遥远的地方",
    "Sincerely",
    "等你下课",
    "明天你好",
    "稻香",
    "鱼",
    "说好的幸福呢",
    "拿走了什么",
    "Speechless (Full)",
    "听见下雨的声音",
    "成全",
    "分手需要练习的",
    "连名代姓",
    "说好不哭",
    "给我一首歌的时间",
    "太阳",
    "花海",
    "倒数",
    "轨迹",
    "句号",
    "有一种悲伤 (电影《比悲伤更悲伤的故事》主題曲) ",
    "雨爱",
    "Secret of my heart",
    "断了的弦",
    "没有如果",
    "需要人陪",
    "飞鸟和蝉-单曲",
    "红莲华",
    "想见你想见你想见你",
    "炎",
    "平凡之路",
    "爱在西元前",
    "听妈妈的话",
    "简单爱",
    "千里之外",
    "开不了口",
    "退后",
    "白色风车",
    "安静",
    "后来的我们",
    "交换余生",
    "你曾是少年",
    "絆ノ奇跡",
    "匿名的好友",
    "Letting Go",
    "达尔文",
    "不将就 (电影《何以笙箫默》片尾曲)",
    "十面埋伏",
    "愿与愁",
    "瞬间的瞬间 (电影《他年她日》主题曲)",
    "黑夜问白天",
    "兜圈",
    "逆光",
    "情歌",
    "野孩子",
]


translit = Transliter(academic)
kks = kakasi()

han_re = re.compile(r"\p{Han}", re.UNICODE)
hangul_re = re.compile(r"\p{Hangul}", re.UNICODE)
kana_re = re.compile(r"[\p{Hiragana}\p{Katakana}]", re.UNICODE)

def conv_char(ch: str) -> str:
    # kks.convert() returns list[dict]; join the hepburn field(s)
    return "".join(p["hepburn"] for p in kks.convert(ch))

def transliterate_char(ch):
    if han_re.match(ch):
        return "".join(lazy_pinyin(ch))
    elif hangul_re.match(ch):
        return translit.translit(ch)
    elif kana_re.match(ch):
        return conv_char(ch)
    else:
        return ch

def transliterate_text(text: str) -> str:
    return "".join(transliterate_char(ch) for ch in text)


def sort_multilang_list(data: Iterable) -> list:
    dddd = {}
    for d in data:
        td = transliterate_text(d).lower()
        dddd[td] = d
    sddd = dict(sorted(dddd.items()))
    return list(sddd.values())


# example


conv_s = sort_multilang_list(ddd)
